name: Deploy to Hostinger Shared Hosting
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Match the Node.js version used in your project
      - name: Install dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ftp://82.25.83.211
          username: u640587353
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./public_html/
          dangerous-clean-slate: true # Optional: Deletes existing files in public_html before uploading